/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (tsType: Omit<PalletType, 'id'>, schemaOptions: { title: 'NewPalletType', exclude: [ 'id' ] })
 */
export interface NewPalletType { 
    /**
     * Pallet Type name
     */
    name: string;
    /**
     * Pallet Type length in mm
     */
    length: number;
    /**
     * Pallet Type width in mm
     */
    width: number;
    /**
     * Pallet Type weight in Kg
     */
    weight: number;
}