/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (tsType: Omit<Stock, 'id'>, schemaOptions: { title: 'NewStock', exclude: [ 'id' ] })
 */
export interface NewStock { 
    palletId?: string;
    productId?: string;
    /**
     * Stock lot
     */
    lot?: string;
    /**
     * Stock expedition date
     */
    expeditionDate?: Date;
    /**
     * Stock serial number
     */
    serialNumber?: string;
    /**
     * Stock quantity
     */
    quantity: number;
}