/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PalletTypeFields } from './palletTypeFields';

export interface PalletTypeFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: Array<string>;
    fields?: PalletTypeFields;
}