/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (tsType: ProductWithRelations, schemaOptions: { includeRelations: true })
 */
export interface ProductWithRelations { 
    /**
     * Product indentifier
     */
    id?: string;
    /**
     * Product name
     */
    code: string;
    /**
     * Product description
     */
    description?: string;
    /**
     * Product image
     */
    image?: string;
    /**
     * Product price
     */
    price: number;
}