/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StockFields { 
    id?: boolean;
    palletId?: boolean;
    productId?: boolean;
    lot?: boolean;
    expeditionDate?: boolean;
    serialNumber?: boolean;
    quantity?: boolean;
}