/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PalletWithRelations } from './palletWithRelations';
import { ProductWithRelations } from './productWithRelations';

/**
 * (tsType: StockWithRelations, schemaOptions: { includeRelations: true })
 */
export interface StockWithRelations { 
    /**
     * Stock indentifier
     */
    id?: string;
    palletId?: string;
    productId?: string;
    /**
     * Stock lot
     */
    lot?: string;
    /**
     * Stock expedition date
     */
    expeditionDate?: Date;
    /**
     * Stock serial number
     */
    serialNumber?: string;
    /**
     * Stock quantity
     */
    quantity: number;
    pallet?: PalletWithRelations;
    product?: ProductWithRelations;
}